function cmaps = buildColormaps()
% Define function handles for creating various colormaps, which can then be
% used in other code. The handles are stored in a struct.
% 
%   Written by Wilfried Beslin
%   Last updated Nov 28, 2023 using MATLAB R2018b
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

cmaps = struct(...
        'parula', @parula,...
        'parula_inverted', @()flipud(parula),...
        'jet', @jet,...
        'jet_inverted', @()flipud(jet),...
        'hsv', @hsv,...
        'hsv_inverted', @()flipud(hsv),...
        'hot', @hot,...
        'hot_inverted', @()flipud(hot),...
        'cool', @cool,...
        'cool_inverted', @()flipud(cool),...
        'spring', @spring,...
        'spring_inverted', @()flipud(spring),...
        'summer', @summer,...
        'summer_inverted', @()flipud(summer),...
        'autumn', @autumn,...
        'autumn_inverted', @()flipud(autumn),...
        'winter', @winter,...
        'winter_inverted', @()flipud(winter),...    
        'gray', @gray,...
        'gray_inverted', @()flipud(gray),...
        'bone', @bone,...
        'bone_inverted', @()flipud(bone),...    
        'copper', @copper,...
        'copper_inverted', @()flipud(copper),...    
        'pink', @pink,...
        'pink_inverted', @()flipud(pink));
end