function cmaps = buildColormaps()
% Define function handles for creating various colormaps, which can then be
% used in other code. The handles are stored in a struct.
% 
%   Written by Wilfried Beslin
%   Last updated Nov 28, 2023 using MATLAB R2018b
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

cmaps = struct(...
        'parula', @parula,...
        'parula_inverted', @()flipud(parula),...
        'jet', @jet,...
        'jet_inverted', @()flipud(jet),...
        'hsv', @hsv,...
        'hsv_inverted', @()flipud(hsv),...
        'hot', @hot,...
        'hot_inverted', @()flipud(hot),...
        'cool', @cool,...
        'cool_inverted', @()flipud(cool),...
        'spring', @spring,...
        'spring_inverted', @()flipud(spring),...
        'summer', @summer,...
        'summer_inverted', @()flipud(summer),...
        'autumn', @autumn,...
        'autumn_inverted', @()flipud(autumn),...
        'winter', @winter,...
        'winter_inverted', @()flipud(winter),...    
        'gray', @gray,...
        'gray_inverted', @()flipud(gray),...
        'bone', @bone,...
        'bone_inverted', @()flipud(bone),...    
        'copper', @copper,...
        'copper_inverted', @()flipud(copper),...    
        'pink', @pink,...
        'pink_inverted', @()flipud(pink),...
        'blue', @blue,...
        'blue_inverted', @()flipud(blue));
end


%% blue -------------------------------------------------------------------
function bl = blue()
% function "blue" taken from the Toothed Whale Detector project, with
% modifications. Original was created by Melissa Soldevilla and was part of
% the Scripps Triton project.
%
%   ORIGINAL TRITON HEADER:
%BLUE    Blue-tone color map.
%   BLUE(M) returns an M-by-3 matrix containing a "blue" colormap.
%   BLUE, by itself, is the same length as the current colormap.
%
%   For example, to reset the colormap of the current figure:
%
%             colormap(blue)
%
%   See also HSV, GRAY, PINK, HOT, COOL, BONE, COPPER, FLAG, 
%   COLORMAP, RGBPLOT.
%
%   9-21-06 mss Ripped from:
%   HOT.m
%   C. Moler, 8-17-88, 5-11-91, 8-19-92.
%   Copyright 1984-2002 The MathWorks, Inc. 
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    % this part has been updated to prevent the creation of figure windows
    % if none exist. The code is from "hot.m". Note that it also used to be
    % within a conditional statement, which has been removed here.
    f = get(groot,'CurrentFigure');
    if isempty(f)
        m = size(get(groot,'DefaultFigureColormap'),1);
    else
        m = size(f.Colormap,1);
    end
    % original "blue" line:
    %m = size(get(gcf,'colormap'),1);
    
    n = fix(1/3*m);

    r = [zeros(2*n,1); (1:m-2*n)'/(m-2*n)];
    g = [zeros(n,1); (1:n)'/n; ones(m-2*n,1)];
    b = [(1:n)'/n; ones(m-n,1)];

    bl = [r g b];
end